import { Expense } from "@/types/Expense";

export const expenses: Expense[] = [
  {
    id: "1",
    nome: "Camisa",
    value: 73.8,
    category: "NOT ESSENTIAL",
    paymentDay: new Date("2024-01-14"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "2",
    nome: "Luz",
    value: 132,
    category: "Essencial",
    paymentDay: new Date("2024-01-02"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "3",
    nome: "Shorts",
    value: 53.21,
    category: "Not Essential",
    paymentDay: new Date("2024-02-14"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "4",
    nome: "Luz",
    value: 110,
    category: "Essencial",
    paymentDay: new Date("2024-02-02"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "5",
    nome: "Restaurante",
    value: 110,
    category: "Not Essential",
    paymentDay: new Date("2024-03-12"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },

  {
    id: "7",
    nome: "Celular",
    value: 753.21,
    category: "Not Essential",
    paymentDay: new Date("2024-02-11"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "8",
    nome: "Notebook",
    value: 2110.2,
    category: "Essencial",
    paymentDay: new Date("2024-02-09"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
  {
    id: "9",
    nome: "Coffe",
    value: 52.2,
    category: "Essencial",
    paymentDay: new Date("2024-03-09"),
    description: "Restaurante, Roupas, Celular, Notebook, Coffe",
    slug: "restaurante-roupas-celular-notebook-coffe",
  },
];
